colorscheme 256_jungle
syntax on

set nowrap "line wrapping
set title "set the term title
set showcmd "show cur command
set showmatch "show matching bracket
set hidden "no nag screens on tag jump
set nocompatible

"Better file handling
set nobackup
set noswapfile
set autowrite

"Perf improvements
set nocursorcolumn
set nocursorline
syntax sync minlines=256

set incsearch     " show search matches as you type
set ignorecase
set smartcase

"Tabs
set autoindent
filetype plugin indent on

"Pathogen
call pathogen#infect()
Helptags

"Leaving modes in Emacs+EVIL feels right
map <C-g> <Esc>
map! <C-g> <Esc>
cmap <C-g> <Esc>

let mapleader=","

nmap <leader>r <ESC>:Ack <C-R><C-W>
nmap <leader>o :CtrlP<CR>
nmap <leader>b :CtrlPBuffer<CR>
nmap <leader>m :CtrlPMRU<CR>

"ctags
nmap <leader>tc :!ctags --extra=+f -R *<CR><CR>
set tags=tags;

"Hitting tab in visual mode fixes indentation on the selected lines
vmap <Tab> =

set wildignore=*.o,*#,*.fasl

set wildmenu
set wildmode=longest,list

let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#whitespace#enabled = 1
let g:airline#extensions#syntastic#enabled = 1
set laststatus=2

:autocmd BufWritePost *.go :silent Fmt

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1

let g:neocomplete#enable_at_startup = 1
" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  "return neocomplete#close_popup() . "\<CR>"
  " For no inserting <CR> key.
  return pumvisible() ? neocomplete#close_popup() : "\<CR>"
endfunction
" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"

autocmd BufWritePre * :FixWhitespace

let g:tmuxcomplete#trigger = ''
